//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnectionTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseResponsibility
    {
        public int ExpenseResponsibilityID { get; set; }
        public string ExpenseResponsibilityType { get; set; }
        public string ResponsibilityMemo { get; set; }
    }
}
