//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnectionTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseDetail
    {
        public int ExpenseDetailsId { get; set; }
        public Nullable<int> ExpenseId { get; set; }
        public Nullable<int> ExpenseResponsibilityId { get; set; }
        public Nullable<int> ExpenseTypeId { get; set; }
        public string Details { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    }
}
