//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnectionTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int ExpenseID { get; set; }
        public Nullable<int> ExpenseDateID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<int> CheckNo { get; set; }
        public Nullable<int> ServiceMonthId { get; set; }
        public Nullable<int> ServiceYearId { get; set; }
        public string TenantNote { get; set; }
        public string OwnerNote { get; set; }
        public string InvoiceNo { get; set; }
        public bool ExpenseCleared { get; set; }
        public Nullable<int> TenderTypeId { get; set; }
    }
}
