//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnectionTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tenant()
        {
            this.TenantLeaseInfoes = new HashSet<TenantLeaseInfo>();
        }
    
        public int TenantId { get; set; }
        public string TenantName { get; set; }
        public string AddlAddress { get; set; }
        public string TenantAddress { get; set; }
        public string TenantCity { get; set; }
        public string TenantState { get; set; }
        public string TenantZip { get; set; }
        public string BillingAddress { get; set; }
        public string BillingAdditional { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingZip { get; set; }
        public string BillingContact { get; set; }
        public string BillingContactPhone { get; set; }
        public string BillingContactEmail { get; set; }
        public string AdditionalInfo { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime ModifiedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TenantLeaseInfo> TenantLeaseInfoes { get; set; }
    }
}
