//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnectionTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantLeaseInfo
    {
        public int TenantLeaseId { get; set; }
        public int TenantId { get; set; }
        public Nullable<decimal> LeaseAmount { get; set; }
        public Nullable<int> SquareFootage { get; set; }
        public Nullable<int> ProRataPercentage { get; set; }
        public Nullable<double> PricePerSquareFoot { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> NNN { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<System.DateTime> LeaseStart { get; set; }
        public Nullable<System.DateTime> LeaseEnd { get; set; }
        public Nullable<System.DateTime> RentCommencement { get; set; }
        public string AdminFee { get; set; }
        public bool ActiveLease { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
